# Generated by Django 4.1.2 on 2022-11-09 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import validation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('senha', models.CharField(max_length=8, unique=True, validators=[validation.validators.valida_senha])),
                ('cpf', models.IntegerField(unique=True, validators=[validation.validators.valida_cpf])),
                ('funcaoEmpresa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
